name: swivel CI/CD 

on:
  push:
    branches: [ main ]

env:
  AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
  AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
  AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_AUD: ${{ secrets.AUTH0_AUD }}

jobs:
  test_push_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install

      - run: yarn build

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and save docker image
        with:
          image: mattsklivas/swivel
          registry: docker.io
          tags: latest 
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

# source : https://github.com/mr-smithers-excellent/docker-build-push
