name: swivel CI testing

on:
  push:
    branches: [ pipeline ]


jobs:
  test_push_request:
    runs-on: ubuntu-latest
    env:
      IMAGENAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
        # add test
      - run: yarn build

      - name: docker image build for deployment
        run: docker build . -t $IMAGENAME

      #from docker hub, push the image to google conatiner registry, and deploy from there. 


# source : https://github.com/mr-smithers-excellent/docker-build-push